sections:
  - name: Getting started
    id: 360004204294
    articles:
      - id: 360022884813
        title: 1/8 Configure Integrations
        file: ../guides/configure-integrations.md
        hash: 77Ino2k5hflcd8uR32AGLYYNw3lW+dw55O9mZo/0XdA=
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022884813-1-8-Configure-Integrations
      - id: 360022705414
        title: 2/8 Search Quickstart
        file: ../guides/quickstart-search.md
        hash: KtVBjMkve4i6v7Xv3sI48wiS7eDGUoAR4ZQTMPJLpbU=
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022705414-2-8-Search-Quickstart
      - id: 360022890073
        title: 3/8 Navigate the Graph
        file: ../guides/quickstart-graph.md
        hash: Vp9Aakhv1lNZGOoXv2aD4IKr/Zk3Fws/Ad2bum85+js=
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022890073-3-8-Navigate-the-Graph
      - title: 4/8 J1QL Query Tutorial
        file: ../guides/tutorial-j1ql.md
        id: 360022720434
        hash: bsB1DhtMYBFZ9O3JV7Q+G5rfawouweoxObdy0F3lAu0=
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022720434-4-8-J1QL-Query-Tutorial
      - title: 5/8 Using Asset Inventory Filters
        file: ../guides/asset-inventory-filters.md
        id: 360022720454
        hash: 9aod3z8IHk9n/v8NN+19QXrxKdWErqpU2LxoxE+7ecs=
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022720454-5-8-Using-Asset-Inventory-Filters
      - title: 6/8 Alerts and Alert Rules
        file: ../guides/manage-alerts.md
        id: 360022720474
        hash: 0HmwxoaQYZIOkuX7pSncCNx2bWbaYq/1s1OzQkxGxyU=
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022720474-6-8-Alerts-and-Alert-Rules
      - title: 7/8 Manage Findings
        file: ../guides/manage-findings.md
        id: 360022901893
        hash: ZFyA8g0XUZDbfnY2v2es/E7OzxjBq0DTneW58w7mUAg=
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022901893-7-8-Manage-Findings
      - title: 8/8 Invite Your Team Members
        file: ../guides/quickstart-invite-users.md
        hash: Pc3WnXrha4d6vqwVP7NfkIgY+ytu6zMnwjBcQU5SOxo=
        id: 360023317474
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360023317474-8-8-Invite-Your-Team-Members
  - name: FAQs
    id: 360002319333
    articles:
      - id: 360022879453
        title: FAQs
        file: ../guides/faqs.md
        hash: XaL8mAo07HfYU4m9rKX1gEZw6rHf3WN8PwzywZKCv6s=
        webLink: 'https://support.jupiterone.io/hc/en-us/articles/360022879453-FAQs'
  - name: User Guides
    id: 360002297174
    articles:
      - title: AWS Resource Configuration Auditing
        file: ../guides/j1-queries-for-aws-config.md
        hash: ci3QMjx9/9HpkTNX13jtpD1yCOhxVyxTN5f44fG/VG4=
        id: 360022721894
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022721894-AWS-Resource-Configuration-Auditing
      - title: AWS Threat Monitoring
        file: ../guides/j1-aws-threat-monitoring.md
        hash: nLJBttq2bjEzdcaBhZozaHzOyNq98JATBYvZzcpelbw=
        id: 360022903333
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022903333-AWS-Threat-Monitoring
      - title: Common Questions and Queries
        file: ../guides/common-questions-and-queries.md
        hash: QdqJe1QsbUj9Az1UFvuEz3fvTsVJkmwVuKuWZojEU84=
        id: 360022721914
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022721914-Common-Questions-and-Queries
      - title: Configure SAML SSO Integration
        file: ../guides/configure-sso-integration.md
        hash: vFOtjING8WDwli/jTY2RSGoGbejhespWSt2tKWfpj9I=
        id: 360022903353
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022903353-Configure-SAML-SSO-Integration
      - title: J1 Endpoint Compliance Agent
        file: ../guides/endpoint-compliance-agent.md
        hash: GakRr9Z7/V0onjadVrHeWM3xrmrKhKoK+EPvtDomfko=
        id: 360022721994
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022721994-J1-Endpoint-Compliance-Agent
  - name: JupiterOne Query Language (J1QL)
    id: 360004247533
    articles:
      - title: J1QL Language Specs
        file: ../docs/jupiterone-query-language.md
        hash: 4a85pGxhV7QQc5BNJ/sIhO61cNqA93tBnK1y89HiIKQ=
        id: 360022722014
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022722014-J1QL-Language-Specs
  - name: API Docs
    id: 360002424353
    articles:
      - title: JupiterOne Platform API
        file: ../docs/jupiterone-api.md
        hash: nQ/sOvCRNcj9BvYzvTldG0qTxMsBl6o/Xgn2SUWOryg=
        id: 360022722094
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022722094-JupiterOne-Platform-API
      - title: JupiterOne Node.js Client and CLI
        file: ../guides/j1-client-and-cli.md
        hash: pbJe9Rk0PcseeE6IYQ9gQXUooWBLwe6H6m6hYKolLVI=
        id: 360022903373
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022903373-JupiterOne-Node.js-Client-and-CLI
  - name: Security and Compliance as Code
    id: 360004326633
    articles:
      - title: SecOps Artifacts as Code
        file: ../guides/secops-artifacts-in-j1.md
        hash: DTHeBtEW4sEd8pHF3+160hDkGqdMJHJTpWtrE16Clkk=
        id: 360022721954
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022721954-SecOps-Artifacts-as-Code
      - title: Detect Suspicious Code Commits
        file: ../guides/detect-suspicious-code-commits.md
        hash: SogW0zK3SQSA6Y7MsUwPYMelU87BYtG8+Yo9TxU3ZF8=
        id: 360022721934
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022721934-Detect-Suspicious-Code-Commits
  - name: Data Model
    id: 360002424373
    articles:
      - title: JupiterOne Graph Data Model
        file: ../docs/jupiterone-data-model.md
        hash: l9ZZN5eHNoNa7RIei82gZTnZjkD9LrRwVSbKVqCrFi4=
        id: 360022903573
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022903573-JupiterOne-Graph-Data-Model
  - name: Data Model Entity Reference
    id: 360004240434
  - name: Managed Integrations
    id: 360004247473
    articles:
      - title: AWS
        file: ../docs/integrations/aws/index.md
        id: 360022721054
        hash: 3zYP5ZwjIn9jM/K61li7WIJWUBpJybDBuW1V+hRT74o=
        webLink: 'https://support.jupiterone.io/hc/en-us/articles/360022721054-AWS'
      - title: BitBucket
        file: ../docs/integrations/bitbucket/bitbucket.md
        id: 360022721074
        hash: EAExn/zIYyCsYBNl8NtMyvFywFfRwNVALIxSFQQNUmk=
        webLink: 'https://support.jupiterone.io/hc/en-us/articles/360022721074-BitBucket'
      - title: Carbon Black PSC
        file: ../docs/integrations/cbdefense/jupiter-integration-cbdefense.md
        id: 360022721094
        hash: n654GBEPOMTgctPScN6aYC8/7UfDU7ymo1ajXLL2zrA=
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022721094-Carbon-Black-PSC
      - title: Github
        file: ../docs/integrations/github/github.md
        id: 360022721114
        hash: NyljXjJQanQ8kuJLfoVJJlhwjt2c83IQI8ecfzwqdZw=
        webLink: 'https://support.jupiterone.io/hc/en-us/articles/360022721114-Github'
      - title: Google
        file: ../docs/integrations/google/jupiter-integration-google.md
        id: 360022902533
        hash: AxstepJE7fiTGnKeD2+Fo78hqBRJ2YxVLt1sL0Sj4Ls=
        webLink: 'https://support.jupiterone.io/hc/en-us/articles/360022902533-Google'
      - title: HackerOne
        file: ../docs/integrations/hackerone/jupiter-integration-hackerone.md
        id: 360022902553
        hash: W+CngaIdr7ucaUpYBw5RA3/UsYCwNTEnXTOfY+Ghi+E=
        webLink: 'https://support.jupiterone.io/hc/en-us/articles/360022902553-HackerOne'
      - title: Jamf
        file: ../docs/integrations/jamf/jupiter-integration-jamf.md
        id: 360022721134
        hash: PyEErFTIgwYuiFEZ2KNoDSjS10R/S3YETnZcY7SB/n4=
        webLink: 'https://support.jupiterone.io/hc/en-us/articles/360022721134-Jamf'
      - title: Jira
        file: ../docs/integrations/jira/jupiter-integration-jira.md
        id: 360022721154
        hash: VKtu2PDvsADbHd55SnuVetka6eL6VlU3Dh6S6/MhReE=
        webLink: 'https://support.jupiterone.io/hc/en-us/articles/360022721154-Jira'
      - title: KnowBe4
        file: ../docs/integrations/knowbe4/index.md
        hash: xZY7ycPqivT4kFU4ZWPJzZzultX7ph/SHpApLpDibDk=
        id: 360023741834
        webLink: 'https://support.jupiterone.io/hc/en-us/articles/360023741834-KnowBe4'
      - title: Okta
        file: ../docs/integrations/okta/jupiter-integration-okta.md
        id: 360022902573
        hash: 9laynxjWwCrnH3n6PuM1Si3K0/NxptODUntMOjnxAok=
        webLink: 'https://support.jupiterone.io/hc/en-us/articles/360022902573-Okta'
      - title: OneLogin
        file: ../docs/integrations/onelogin/jupiter-integration-onelogin.md
        id: 360022721174
        hash: wkaS2UQaBWa1puttqqdDI1nb3y2xCfgu08va6sXVdDA=
        webLink: 'https://support.jupiterone.io/hc/en-us/articles/360022721174-OneLogin'
      - title: OpenShift
        file: ../docs/integrations/openshift/jupiter-integration-openshift.md
        id: 360022721194
        hash: XsXNrsYId9RJybpV1oG6UJpBimd2q1nA0+BPKryw6Cs=
        webLink: 'https://support.jupiterone.io/hc/en-us/articles/360022721194-OpenShift'
      - title: SentinelOne
        file: ../docs/integrations/sentinelone/jupiter-integration-sentinelone.md
        id: 360022721214
        hash: 2E2BshP//MYCMtd/R0QoZB4MvOvoqWQMgU5aY7nMo/0=
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022721214-SentinelOne
      - title: Tenable Cloud
        file: >-
          ../docs/integrations/tenable-cloud/jupiter-integration-tenable-cloud.md
        id: 360022902593
        hash: SYlVT9qX0XYaHNpiTzMBjDKE7RtFNn9HP0tlw+8tp3c=
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022902593-Tenable-Cloud
      - title: Threat Stack
        file: ../docs/integrations/threatstack/index.md
        hash: ERgUb92Y0znDfDek0Bas6m7G6DewqaR/gTMinqchy9w=
        id: 360023924853
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360023924853-Threat-Stack
      - title: Veracode
        file: ../docs/integrations/veracode/jupiter-integration-veracode.md
        id: 360022721234
        hash: 97tu46fN+RzZ+tQVKCDwKgQA3fFzJN3dO/4FZyl85W8=
        webLink: 'https://support.jupiterone.io/hc/en-us/articles/360022721234-Veracode'
      - title: Wazuh
        file: ../docs/integrations/wazuh/jupiter-integration-wazuh.md
        id: 360022721254
        hash: OG9PYg7VPUT8obZazaTAnFUOC5Z6klC6DZk6LMlgXmw=
        webLink: 'https://support.jupiterone.io/hc/en-us/articles/360022721254-Wazuh'
      - title: WhiteHat Security
        file: ../docs/integrations/whitehat/jupiter-integration-whitehat.md
        id: 360022721274
        hash: dUJiyRbsqpRQ96T960PvlSwM31rXpbwElGD8ABv5tVI=
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022721274-WhiteHat-Security
  - name: Release Notes
    id: 360002427353
    articles:
      - title: 2019.23 Release
        file: ../release-notes/2019-23.md
        hash: vxHzcbpK9I7N3tylPDcOrM002I+UDRKZIDqXoRm4MeE=
        id: 360024035673
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360024035673-2019.23-Release
      - title: 2019.22 Release
        file: ../release-notes/2019-22.md
        hash: OO+b9gz/3vOLW7L6lftwet4BAlH6YvzUOZn0P6/NRYs=
        id: 360024035693
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360024035693-2019.22-Release
      - title: 2019.21 Release
        file: ../release-notes/2019-21.md
        hash: pLSwzipZUtnDtv4SdM4XwsrEWGW4JXlkGAsGV3rsuZw=
        id: 360022903253
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022903253-2019.21-Release
      - title: 2019.20 Release
        file: ../release-notes/2019-20.md
        hash: 3xl74T/TxZNJsZC0+RgKkzuQjCiCSLUXoZl38Jc/1pQ=
        id: 360022903213
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022903213-2019.20-Release
      - title: 2019.19 Release
        file: ../release-notes/2019-19.md
        hash: np8wU0NK3rfCG6b3O5VCVY/Ye3Vyxt5r6a46rMJ6Vno=
        id: 360022903193
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022903193-2019.19-Release
      - title: 2019.18 Release
        file: ../release-notes/2019-18.md
        id: 360022721494
        hash: vwm0M5zZ2bMKBaPG1VU8pCK8591dAA4hc2iyt45bhf8=
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022721494-2019.18-Release
      - title: 2019.17 Release
        file: ../release-notes/2019-17.md
        id: 360022902833
        hash: kodVJe926tm4S5k37QRXAmnlXcBhthIs/6QykxnTD04=
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022902833-2019.17-Release
      - title: 2019.16 Release
        file: ../release-notes/2019-16.md
        id: 360022902813
        hash: 9bQgOlsOy9IM7jpbupbra43aYdjq2B2U12tO49ldQqg=
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022902813-2019.16-Release
      - title: 2019.15 Release
        file: ../release-notes/2019-15.md
        id: 360022721434
        hash: XMe/hnR1C3Mf4MwdOLhBhUsaFSLiTun9kjxZixmBKqA=
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022721434-2019.15-Release
      - title: 2018.14 Release
        file: ../release-notes/2018-14.md
        id: 360022721414
        hash: o4i7O4pmO/XFOu5A7jsG2FCG+8ljCLIvjo7+YvVVCMI=
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022721414-2018.14-Release
      - title: 2018.13 Release
        file: ../release-notes/2018-13.md
        id: 360022902753
        hash: pMuSff8LE0F08hBiJJ7CHW6df2S3WcTtlsMjRcwyFS0=
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022902753-2018.13-Release
      - title: 2018.12 Release
        file: ../release-notes/2018-12.md
        id: 360022902733
        hash: 54Gu0IqKUiev5Jzr6M0yi2bdOgzjP32Tm7ob+ocrKX8=
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022902733-2018.12-Release
      - title: 2018.11 Release
        file: ../release-notes/2018-11.md
        id: 360022721394
        hash: hZxjUEg2e8V7lVXuRB7YQKZoiyg4Wf4e40+uZNC3xDk=
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022721394-2018.11-Release
      - title: 2018.10 Release
        file: ../release-notes/2018-10.md
        id: 360022721374
        hash: 2V6qxyEyRNzbQLyqT75S3RmVnUz4L6Gbe4/EvpuX7XU=
        webLink: >-
          https://support.jupiterone.io/hc/en-us/articles/360022721374-2018.10-Release
